# Generated by Django 5.2.7 on 2025-11-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_api', '0008_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title', 'content'], name='news_api_ar_title_a8e265_idx'),
        ),
    ]
